#!/usr/bin/env bash
# Windows (git bash) 向けに、repo の設定ファイルを HOME / AppData 配下へコピーする。
# symlink は使わない。理由: Windows の symlink は開発者モードか管理者権限が要る。
# repo -> HOME の一方通行。repo 側を更新したらもう一度流す。既存ファイルは .bak.YYYYMMDDHHMMSS に退避する。
set -euo pipefail

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# HOME と同じく APPDATA も env で差し替えられる。一時ディレクトリで検証するときに使う。
APPDATA_DIR="$(cygpath -u "${APPDATA:?APPDATA is not set (run from git bash on Windows)}")"

info() { printf '[copy-configs] %s\n' "$*"; }
die() { printf '[copy-configs] ERROR: %s\n' "$*" >&2; exit 1; }

# repo 内の path (repo root からの相対) をコピーする。
copy_path() {
  place_path "$DOTFILES_ROOT/$1" "$2"
}

place_path() {
  local src="$1"
  local dest="$2"
  local backup

  [[ -e "$src" ]] || die "source not found: $src"
  mkdir -p "$(dirname "$dest")"

  # 中身が同じなら何もしない。再実行で .bak が増え続けないようにする。
  if [[ -d "$src" && -d "$dest" ]] && diff -rq "$src" "$dest" >/dev/null 2>&1; then
    info "unchanged: $dest"
    return 0
  fi
  if [[ -f "$src" && -f "$dest" ]] && cmp -s "$src" "$dest"; then
    info "unchanged: $dest"
    return 0
  fi

  if [[ -e "$dest" ]]; then
    backup="$dest.bak.$(date +%Y%m%d%H%M%S)"
    info "backup: $dest -> $backup"
    mv "$dest" "$backup"
  fi

  cp -R "$src" "$dest"
  info "copied: $dest"
}

# mac の ctrl+X の割り当てのうち、Windows 標準の ctrl+X (mac の cmd+X 相当) を優先したいもの。mac 側の割り当ては alt+X に逃がす。
# - f: 検索。mac の toggleFold は alt+f
# - d: 次の一致を選択に追加。mac の decrementNumberByOne は alt+d
# - i: サジェスト表示。mac の incrementNumberByOne は alt+i
# - [ / ]: インデント増減。mac のエディタグループ / terminal 移動は alt+[ / alt+]
WINDOWS_STANDARD_CTRL_KEYS=(f d i '[' ']')

# mac の VSCode keybindings を Windows 向けに読み替えて stdout に出す。
# Windows も CapsLock = Ctrl なので mac の ctrl はそのまま。mac の cmd は Windows の ctrl にする。
# - ctrl+cmd / cmd+ctrl は ctrl+alt にする。理由: 単純置換だと ctrl+ctrl+X になり無効
# - WINDOWS_STANDARD_CTRL_KEYS の ctrl+X は alt+X にする
# - cmd+w は読み替えない。理由: terminal kill なので、ctrl+w にすると bash の単語削除で terminal が落ちる
# - cmd+shift+i は読み替えない。理由: chat を潰す設定で、ctrl+shift+i にすると incrementSelection を潰す。chat は settings で無効化済み
vscode_keybindings_for_windows() {
  local key pattern
  local yield_rules=()
  for key in "${WINDOWS_STANDARD_CTRL_KEYS[@]}"; do
    # [ ] などを正規表現の literal にする
    pattern="$(printf '%s' "$key" | sed 's/[][\\.*^$+?(){}|/]/\\&/g')"
    yield_rules+=(-e "s/\"key\": \"ctrl\\+$pattern\"/\"key\": \"alt+$key\"/")
  done

  sed -E \
    -e '1a\// Generated by windows/copy-configs.sh from vscode/keybindings.json (cmd -> ctrl). Edit the repo file instead.' \
    -e '/"key": "cmd\+(shift\+i|w)"/b' \
    "${yield_rules[@]}" \
    -e 's/(ctrl\+cmd|cmd\+ctrl)\+/ctrl+alt+/g' \
    -e 's/cmd\+/ctrl+/g' \
    "$DOTFILES_ROOT/vscode/keybindings.json"
}

# mac の VSCode settings に windows/vscode-settings.json を上書き merge して stdout に出す。
# Windows 版 jq は -b を付けても CRLF を出すので tr で落とす。
vscode_settings_for_windows() {
  jq -s '.[0] * .[1]' "$DOTFILES_ROOT/vscode/settings.json" "$DOTFILES_ROOT/windows/vscode-settings.json" | tr -d '\r'
}

info "dotfiles root: $DOTFILES_ROOT"

copy_path windows/gitconfig "$HOME/.gitconfig"
copy_path git/gitignore_global "$HOME/.gitignore_global"
copy_path mise/win.toml "$HOME/.config/mise/config.toml"
copy_path gh/config.yml "$APPDATA_DIR/GitHub CLI/config.yml"
generated_dir="$(mktemp -d)"
trap 'rm -rf "$generated_dir"' EXIT
vscode_settings_for_windows > "$generated_dir/settings.json"
place_path "$generated_dir/settings.json" "$APPDATA_DIR/Code/User/settings.json"
vscode_keybindings_for_windows > "$generated_dir/keybindings.json"
place_path "$generated_dir/keybindings.json" "$APPDATA_DIR/Code/User/keybindings.json"

copy_path ai/CLAUDE.md "$HOME/.claude/CLAUDE.md"
copy_path ai/CLAUDE.md "$HOME/.codex/AGENTS.md"
# chrome-connect は zsh 製の bin/chrome-devtools に依存するので載せない。
for skill in gsheet show-me why-me; do
  copy_path "ai/skills/$skill" "$HOME/.claude/skills/$skill"
  copy_path "ai/skills/$skill" "$HOME/.codex/skills/$skill"
done

# git bash で動く bash 製のコマンドだけ。zsh 製のものは Windows に zsh が無いので載せない。
for cmd in gsheet gsheet.cmd pdf2png; do
  copy_path "bin/$cmd" "$HOME/.local/bin/$cmd"
done
